exports.TCP_PORT = 7070
exports.WS_PORT = 7071
exports.WEB_PORT = 7080
exports.SERVER_NAME = 'Unnamed Aurorachat V7 Server'
exports.MAX_ROOM_HISTORY = 128
exports.USER_SAVE_INTERVAL = 720
exports.PLUGINS = ['hausmeister']
exports.PLUGIN_CONFIG = {
    hausmeister: {
        name: '[HAUSMEISTER]',
        prefix: '!haus'
    },
    discordbridge: {
        channelId: '<channelid for discord bridge>',
        token: '<token for discord bridge>',
        room: 'general' // room to mirror
    }
}
exports.SERVER_RULES = `#1 Be Respectful
Please respect other members, whether that be their religion, identity, sexuality, or beliefs. We however, do not tolerate bigotry or hateful beliefs. We do not tolerate slurs, either.

#2 No NSFW
Do not share or discuss NSFW content. This includes gore and sexual content.

#3 No Self-Promo
Please do not promote your own content anywhere.

#4 Respect Channel Topics
Please respect the topics of each channel. While not heavily enforced, if you stray too far, please redirect your conversation.

#5 No Politics
Please do not discuss political topics in our server. These conversations can lead to heated debates or dark subjects, which we do not want in our server.

#6 No AI-Generated content
We have a strict no-AI policy. Do not share any content generated by AI, whether it be images, "music", or chatbots. You may discuss AI topics, but do not share generative AI resources.

#7 No Venting
Please do not vent in our server. Neither our staff or members are therapists, and we cannot properly help you. Please reach out to a trusted source if you are able. Venting will result in a 10 minute timeout. Talking about life is allowed.

#8 No Dark Topics
Please do not joke or discuss about serious topics, not limited to but including, suicide, self harm, excessive violence, abuse, etc.

#9 No Discussing Punishments
Please do not discuss/ask why a member got a punishment. If they were an important member of the community, an explanation will be provided soon.`
