exports.TCP_PORT = 7070
exports.WS_PORT = 7071
exports.WEB_PORT = 7080
exports.SERVER_NAME = 'Unnamed Aurorachat V7 Server'
exports.MAX_ROOM_HISTORY = 128
exports.USER_SAVE_INTERVAL = 720
exports.REGISTER_DISABLED = false
exports.SPAM_INTERVAL = 5000
exports.SPAM_COUNT = 15
exports.SPAM_COUNT_KICK = 25
exports.PLUGINS = ['hausmeister', 'jackbot']
exports.PLUGIN_CONFIG = {
    hausmeister: {
        name: '[HAUSMEISTER]',
        prefix: '!haus',
        bulletinLimit: 32
    },
    discordbridge: {
        channelId: '<channelid for discord bridge>',
        token: '<token for discord bridge>',
        userId: '<user id for discord bridge>',
        room: 'general' // room to mirror
    },
    jackbot: {
        name: '[JACKBOT]'
    }
}
exports.DEFAULT_MOTD = `Welcome to <%- servername %>, <%- username %>!

The admins of this server haven't bothered to change default MOTD!
Please nag them about this!
`
exports.SERVER_RULES = `#1 Be Respectful
Please respect other members, whether that be their religion, identity, sexuality, or beliefs. We however, do not tolerate bigotry or hateful beliefs. We do not tolerate slurs, either.

#2 No NSFW
Do not share or discuss NSFW content. This includes gore and sexual content.

#3 No Self-Promo
Please do not promote your own content anywhere.

#4 Respect Channel Topics
Please respect the topics of each channel. While not heavily enforced, if you stray too far, please redirect your conversation.

#5 No Politics
Please do not discuss political topics in our server. These conversations can lead to heated debates or dark subjects, which we do not want in our server.

#6 No AI-Generated content
Content generated by AI is allowed as long as you know it was made with AI.

#7 No Venting
Please do not vent in our server. Neither our staff or members are therapists, and we cannot properly help you. Please reach out to a trusted source if you are able. Venting will result in a 10 minute timeout. Talking about life is allowed. Slight venting (e.g "i feel kinda bad" and similar) is allowed but make sure to moderate it.

#8 No Dark Topics
Please do not joke or discuss about serious topics, not limited to but including, suicide, self harm, excessive violence, abuse, etc.

#9 No Discussing Punishments
Please do not discuss/ask why a member got a punishment. We can punish people if we think they deserve it (e.g. not listed in the rules, or something else)

#10 No Ragebait
Please do not purposely try to enrage members of this server, and if a member of this server appears to be getting enraged, please do not try to amplify that rage.
If a mod is ever breaking rules, please reach out to our @Administrator and we will take care of it.`
